# Needs variables:
#  * GIT_AUTHOR_EMAIL
#  * SSH_PRIVATE_KEY
#  * SSH_PUBLIC_KEY
job:on-schedule:
    image: alpine
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
    before_script:
        - apk update
        - apk add wget git openssh
        - eval `ssh-agent -s`
        - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_PUBLIC_KEY" >> ~/.ssh/id_ed25519.pub
    script:
        - ./.gitlab-ci-update.sh
